name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Build and deploy the React app'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Setup credentials to access private repositories
      run: git config --global url.https://${{ secrets.MY_PAT }}@github.com/.insteadOf https://github.com/

    - name: Configure Git identity
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Build the React app
      run: npm run build

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx gh-pages -d build